export const deepClone = <T>(obj: T): T => JSON.parse(JSON.stringify(obj)); // extremely expensive to use; don't use casually...

export const toUniqueArray = <T>(arr: T[]): T[] => [...new Set(arr)];
